### PR TITLE
Fix `sepBy` and `sepEndBy`

### LINKED ISSUE #113: `sepEndBy` behaves incorrectly (?)
```purescript
elemA = PS.string "A"
elemB = PS.string "B"
sep = PS.string ";"
parse = flip P.runParser do Tuple <$> PC.sepEndBy elemA sep <*> elemB
```

This now fails:
```purescript
parse "A;B"
```

Prior to v6 it succeeded. Copying the old implementation of `sepEndBy` locally and implementing `parse` with that restores the original behaviour. 

I'd say this behaviour is wrong too, it's not just that it's different now - as far as I can tell, if there's a trailing separator, and then any other input follows, the combinator fails now.

### PR DESCRIPTION
**Pull request by yzyzsun**
**Description of the change**

This pull request fixed #113.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation in the README and/or documentation directory
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by robertdp** [comment]
It seems like `endBy` and `endBy1` also need attention. This first test passes, but the next 2 fail:
```purs
  parseTest "a,a,a," (cons "a" (cons "a" (cons' "a" Nil))) $ do -- existing
    as <- string "a" `endBy1` string ","
    eof
    pure as
  parseTest "a,a,a" (cons "a" (cons' "a" Nil)) $ do -- new
    as <- string "a" `endBy1` string ","
    _ <- string "a"
    pure as
  parseTest "a,a,a" (Cons "a" (Cons "a" Nil)) $ do -- new
    as <- string "a" `endBy` string ","
    _ <- string "a"
```

**Comment by robertdp** [comment]
And I could be wrong, but do `optional` and `option` also need this? For both of these, if the supplied parser consumes input and fails then the alt behaviour will be skipped. I would be great to hear from someone with more experience. @garyb ?

**Comment by yzyzsun** [comment]
@robertdp Thank you for pointing these issues out. I have just checked the implementation of Haskell's [Parsec](https://hackage.haskell.org/package/parsec-3.1.14.0/docs/src/Text.Parsec.Combinator.html#endBy1) library and found they cannot parse your new test cases either. Maybe my latest commit on `endBy` is not expected? I'd like to hear from @garyb too.

Btw, although adding `try` is the simplest way to fix `sepBy` and `sepEndBy`, I now realize this could lead to uninformative error messages. Is it better to rewrite them using the original mutual recursive style?

**Comment by robertdp** [comment]
@yzyzsun Sorry for thinking aloud in your PR. I only just discovered this problem caused by my PR, so I've been digging into this lib and comparing it with Parsec to try and understand what I was missing.

This definitely needs input from the maintainers (and people who understand and use the lib) but I would suggest undoing all the changes from my PR, including removing the use of `NonEmptyList`. This puts it back to the Parsec-style mutually recursive implementation. If we want to have combinators that return `NonEmptyList`, they could be identically-named but in a new module called `Text.Parsing.Parser.Combinators.NonEmpty`.

**Comment by yzyzsun** [comment]
@robertdp Never mind about that! Actually I agree with your suggestion since it can easily bring everything back to order.

**Comment by garyb** [comment]
Thanks for kicking this off @yzyzsun!

**Pull request closed without merging**
