### PR TITLE
Add eitherP for combining two alternatives.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Needed this from megaparsec style Haskell code and couldn't find an equivalent.

### CODE REVIEW

**Comment by paf31** [comment]
I think this could possibly go into `purescript-control`. Also, it only needs `Alt`, right?

**Comment by garyb** [comment]
^ I think it would have to go in `purescript-either` to make the dependencies work out.

**Comment by tmcgilchrist** [comment]
I'm still getting used to the package setup in purescript and where things live.
Happy to move this to either place, just let me know which is the preferred one.

**Comment by tmcgilchrist** [comment]
Closing in favour of the linked PR.

**Pull request closed without merging**
