### PR TITLE
Add primitive Parsing.DataView parsers

### PR DESCRIPTION
**Pull request by jamesdbrock**
From https://github.com/jamesdbrock/purescript-parsing-dataview

Prior attempt: #89

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation in the README and/or documentation directory
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by garyb** [comment]
This seems like some strange stuff to add to the basic parsing library, what was wrong with it living in its own library?

**Comment by jamesdbrock** [comment]
> This seems like some strange stuff to add to the basic parsing library, what was wrong with it living in its own library?

That’s a reasonable position to take.

I guess the question is, do we want this to be a basic parsing library, or do we want this to to be a comprehensive batteries-included parsing library? I like the latter.

I tried this before in 2020 #89 . That PR would have introduced dependencies from outside __purescript-contrib__. This PR has no outside dependencies.

**Comment by garyb** [comment]
I guess my disagreement with this attempt to include them is that it makes the library unportable - that might technically be true for other reasons just now, but it would become inescapable fact if we included these, since `ArrayBuffer` and friends are completely JS-specific types.

**Comment by jamesdbrock** [comment]
> I guess my disagreement with this attempt to include them is that it makes the library unportable 

Yeah that's a very good point.

**Comment by jamesdbrock** [comment]
I moved the __parsing-dataview__ package to __rowtype-yoga__ instead of including it in this package.

**Pull request closed without merging**
