### PR TITLE
Updates for purescript compiler v0.12.0

### PR DESCRIPTION
**Pull request by joncfoo**
- updated packages to match packages compatible with compiler v0.12.0
- added psc-package.json tagged at v0.12.0
- updated function imports
- removed effect rows
- changed combinator associativity (see #74)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Hey folks! Any updates on this one? Looks like the  `purescript-formatters` update by @justinw requires this to be merged / released before it can be updated:

https://github.com/slamdata/purescript-formatters/pull/47

**Comment by paf31** [comment]
There was some discussion around code units vs code points on `string-parsers` that is probably relevant here too.

**Comment by joncfoo** [comment]
> There was some discussion around code units vs code points on string-parsers that is probably relevant here too.

Is it purescript-contrib/purescript-string-parsers#43 ?

**Comment by paf31** [comment]
Yes. Maybe this library could support both options, actually.

**Comment by whoadave** [comment]
Does that have to block this PR though?

**Comment by thomashoneyman** [comment]
While the concern isn't exactly the same, I'd like to quote my comment from another thread here just for visibility's sake:

> @paf31 Is it possible to release a new version of this library for 0.12 compatibility alone? 
> 
> It would make for an easier transition for folks like @justinwoo and my team and likely less stress for you if this (and libraries like `parsing`) were available in their current form for 0.12, and later, when you have time & at your convenience, another update could be made to break `Event` out to a separate package.
> 
> Halogen updated this way and it's been quite nice; they get to relax and take their time working on the next big improvement to the library, but the rest of the dependent ecosystem can complete the transition to 0.12 without relying on forks.

**Comment by thomashoneyman** [comment]
Update on formatters: open PR relying on this branch, linking here in order to make sure to stay in sync if there are changes here or another update is done instead:

https://github.com/slamdata/purescript-formatters/pull/48

**Comment by paf31** [comment]
I'm no longer maintainer of this library.

**Comment by garyb** [comment]
Thanks! I went with just making it a "0.12 compatibility" release for now. I think maybe we could support both code units and points though, by making modules under `String` / `Token` that allow the user to choose what they're interested in. Perhaps the default should be `CodePoint`s, despite the insane overhead, since `CodeUnit`s are kinda "wrong".

**Pull request merged**
