### PR TITLE
Parser.String.regex

### LINKED ISSUE #141: regex primitive parser
A regex [`regex`](https://pursuit.purescript.org/packages/purescript-string-parsers/6.0.1/docs/Text.Parsing.StringParser.CodePoints#v:regex) primitive parser would be nice.

_Originally posted by @jamesdbrock in https://github.com/purescript-contrib/purescript-parsing/issues/110#issuecomment-925686569_

### PR DESCRIPTION
**Pull request by jamesdbrock**
Add a `regex` parser.

Resolves #141 

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation in the README and/or documentation directory
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by natefaubion** [comment]
What was the reason for taking an options object instead of using the `RegexFlags` Semigroup instance?

**Comment by jamesdbrock** [comment]
> What was the reason for taking an options object instead of using the `RegexFlags` Semigroup instance?

Yeah I see what you mean. If the type of this parser were `regex :: RegexFlags -> String -> ParserT s m a` then we could call it like `regex (dotAll <> ignoreCase <> unicode) "x*"`. That’s a pretty nice API, and clearly that’s what the Semigroup instance is for.

But I’m not sure that it handles default flags well. Two of the `regex` parser flags default to `true`. In the documentation for [`Parser.String.regex`](https://pursuit.purescript.org/packages/purescript-parsing/docs/Text.Parsing.Parser.String#v:regex) I hint that the users might want to turn off the `dotAll` flag. (And possibly the `unicode` flag?) In which case it’s nice to be able to write `regex {dotAll: false} "x*"`.

But I don’t know, that’s a pretty rare case, and it may never come up, and if it does come up then the user could set the `dotAll` flag to false by building the flags like `regex unicode "x*"`. Though when we write it that way the author’s intent to set `dotAll` to false is less clear than `regex {dotAll: false} "x*"`.

Another problem with the Semigroup API is that if the user wants to turn on `ignoreCase` then they might write `regex ignoreCase "x*"`, which would accidentally turn off the `dotAll` and `unicode` flags.

The part that troubles me the most is that I defined a [`RegexFlagsRow`](https://pursuit.purescript.org/packages/purescript-parsing/docs/Text.Parsing.Parser.String#t:RegexFlagsRow) in the parsing package. I would prefer to use only definitions from `Data.String.Regex`.

I would like to hear your advice about this.

**Comment by chtenb** [comment]
> `regex (dotAll <> ignoreCase <> unicode) "x*"`

How would you turn off flags given a semigroup flags value? Or is that not possible?

**Comment by jamesdbrock** [comment]
> If you feel very strongly that these defaults are correct for 95%+ of use cases,

I'm not at all sure that these defaults are correct.

> maybe the default `regex` should provide no configuration? You can then provide a `regexWithFlags` version, and partially apply it for the default case `regex = flip regexWithFlags (unicode <> dotAll)`. 

Ok I like that, I'll change it so it works that way.

**Pull request merged**
